### Output configuration
#
# Default wallpaper
#
# NOTE: I changed the default location of the pictures folder.
# The current default `Pictures` folder is defined in `~/.config/user-dirs.dirs` (that file defines all the XDG default folders..)
# Using `exec sh -c` ensures this is only called once during login.
exec sh -c 'pkill swaybg; swaybg -i "$(xdg-user-dir PICTURES)/wallpapers/lynch/1547201.jpg" -m fill'

# You can get the names of your outputs by running: swaymsg -t get_outputs
# See kanshi settings for more information
