# Gruvbox Light
set -g status-style "bg=colour187,fg=colour237"

set -g status-left-length 30
set -g status-left "#[bg=colour136,fg=colour230,bold] #S #[bg=colour187,fg=colour136,nobold] "

set -g status-right-length 40
set -g status-right "#[fg=colour243] %d %b  #[fg=colour237,bold]%H:%M "

set -g window-status-format         " #I:#W#{window_flags} "
set -g window-status-current-format "#[bg=colour136,fg=colour230,bold] #I:#W #[bg=colour187,fg=colour136,nobold] "
set -g window-status-style          "fg=colour243"
set -g window-status-current-style  "fg=colour136"

set -g pane-border-style        "fg=colour180"
set -g pane-active-border-style "fg=colour136"

set -g message-style "bg=colour136,fg=colour230,bold"
